name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  android-test:
    name: Run Android API-${{ matrix.api-level }} Test
    # Requires a "larger runner", for nested virtualization support
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [26,27,28]
    steps:
#       # See https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
#      - name: Enable KVM group perms…
#        run: |
#          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
#          sudo udevadm control --reload-rules
#          sudo udevadm trigger --name-match=kvm

      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run android tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Create Test Report
        if: success() || failure()
        run: find . -type d -name 'reports/androidTests/connected/' | zip -@ -r build-reports.zip

      - name: Upload results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ job.status }}
          path: build-reports.zip
